### ISSUE TITLE
Observaciones

### ISSUE THREAD

**Issue by ggallici** [jlsuh/dds-macowins#1]
Buenas, Te voy marcando un par de cositas para que tengas en cuenta:

1. Tenés un bug en el mensaje `gananciasDelDia` (te está devolviendo las ganancias acumuladas de **todos** los días). Para poder obtener las del día de la fecha necesitarías tener un atributo `fecha` en la `Venta` y, antes de sumar las ventas, filtras por las que tengan fecha de hoy. Si hubieras hecho mas tests, te hubieras dado cuenta :P
2. Usar `String` para modelar el tipo de prenda no es la mejor idea (y menos, hacer un subclaseo solo por eso). Imaginate que quisiera filtrar "pantalones", tendría que acordarme como es la cadena de caracteres que representa ese tipo ("Pantalones", "PANTALONES", "pantalón", etc) y, peor todavía, repetir esa cadena en cada lugar que quiera filtrar.
Por eso existen los `Enums` que representan un conjunto acotado de valores, y que, sumados a una única clase `Prenda` te permitirían hacer algo como esto:

```java
public class Prenda {
    ...
    private Tipo tipo;
}

public enum Tipo {
    SACO, PANTALON, CAMISA
}

//para crear una camisa
Prenda prenda = new Prenda(..., Tipo.CAMISA);

//para filtrar pantalones
prendas.stream().filter(p -> p.getTipo().equals(Tipo.PANTALON));
```

Ahora, contestando un poco tus dudas:
1. Cuando usar clases abstractas y cuando usar interfaces?
Bueno, eso depende de si hay o no código para "compartir" a las clases hijas.
Si no hay ninguna porción de código que se repita en el comportamiento entre 2 subclases de una clase abstracta, entonces conviene refactorizar en una interface.
Por otro lado, un detalle no menor a tener en cuenta, es que la herencia es un arma de un solo tiro. **No se puede heredar de más de una clase**. Así que si tenes codigo que se comparte, pero ya estas usando herencia en esa clase, vas a tener que ir por otra solución.
2. Hay formas de hacer que asegurar que Macowins tenga una única instancia?
Si, hay formas, pero no te quiero spoilear porque lo vamos a ver dentro de poco :P.
Igualmente pensa esto: Por qué querrías limitar la cantidad de instancias que podes tener? Si solo queres una, instancia la clase una única vez y listo.

Espero haber evacuado tus dudas.
Con respecto a la solución, está bastante bien :partying_face:

**Comment by jlsuh** [comment]
Buenas @ggallici !
Me acerco a esta vez a consultarte, si me faltaría algún caso de test que contemplar, o si los tests están bien o mal encaminados.
No se me ocurrieron más casos de los que contemplé, quería saber si estaría contemplando la mayoría de los casos.
Saludos !
